[theme]
primaryColor = "#FEC30D"     # iLabs Gold
backgroundColor = "#FFFFFF"  # White Background
secondaryBackgroundColor = "#262730" # Dark Tech Sidebar
textColor = "#31333F"        # Dark Grey Text
font = "sans serif"
